version: 0.2

phases:
  install:
    commands:
      # 安裝 kubectl
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.27.1/2023-04-19/bin/linux/arm64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      # 安裝 helm
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - chmod +x get_helm.sh
      - ./get_helm.sh
  pre_build:
    commands:
      - docker login --username=$USER --password=$PASS
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $REGION
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker build --platform linux/arm64 -f Dockerfile -t "doctorash/gamania" .
  post_build:
    commands:
      - docker push "doctorash/gamania"
      - helm upgrade --install nginx ./helm -f helm/values.yaml