version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - docker login --username=$USER --password=$PASS
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker build --platform linux/arm64 -f Dockerfile -t "doctorash/gamania" .
  post_build:
    commands:
      - docker push "doctorash/gamania"